
export const ADD_BANNER_REQUEST = "ADD_BANNER_REQUEST";
export const ADD_BANNER_SUCCESS = "ADD_BANNER_SUCCESS";
export const ADD_BANNER_RESET = "ADD_BANNER_RESET";
export const ADD_BANNER_FAIL = "ADD_BANNER_FAIL";

export const DELETE_BANNER_REQUEST = "DELETE_BANNER_REQUEST";
export const DELETE_BANNER_SUCCESS = "DELETE_BANNER_SUCCESS";
export const DELETE_BANNER_RESET = "DELETE_BANNER_RESET";
export const DELETE_BANNER_FAIL = "DELETE_BANNER_FAIL";

export const ALL_BANNERS_REQUEST = "ALL_BANNERS_REQUEST";
export const ALL_BANNERS_SUCCESS = "ALL_BANNERS_SUCCESS";
export const ALL_BANNERS_FAIL = "ALL_BANNERS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";