
export const ORDERS_CHART_REQUEST = "ORDERS_CHART_REQUEST";
export const ORDERS_CHART_SUCCESS = "ORDERS_CHART_SUCCESS";
export const ORDERS_CHART_RESET = "ORDERS_CHART_RESET";
export const ORDERS_CHART_FAIL = "ORDERS_CHART_FAIL";

export const SALES_CHART_REQUEST = "SALES_CHART_REQUEST";
export const SALES_CHART_SUCCESS = "SALES_CHART_SUCCESS";
export const SALES_CHART_RESET = "SALES_CHART_RESET";
export const SALES_CHART_FAIL = "SALES_CHART_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";