
export const ADD_NURSERY_REQUEST = "ADD_NURSERY_REQUEST";
export const ADD_NURSERY_SUCCESS = "ADD_NURSERY_SUCCESS";
export const ADD_NURSERY_RESET = "ADD_NURSERY_RESET";
export const ADD_NURSERY_FAIL = "ADD_NURSERY_FAIL";

export const DELETE_NURSERY_REQUEST = "DELETE_NURSERY_REQUEST";
export const DELETE_NURSERY_SUCCESS = "DELETE_NURSERY_SUCCESS";
export const DELETE_NURSERY_RESET = "DELETE_NURSERY_RESET";
export const DELETE_NURSERY_FAIL = "DELETE_NURSERY_FAIL";

export const ALL_NURSERYS_REQUEST = "ALL_NURSERYS_REQUEST";
export const ALL_NURSERYS_SUCCESS = "ALL_NURSERYS_SUCCESS";
export const ALL_NURSERYS_FAIL = "ALL_NURSERYS_FAIL";

export const ASSIGN_TO_NURSERY_REQUEST = "ASSIGN_TO_NURSERY_REQUEST";
export const ASSIGN_TO_NURSERY_SUCCESS = "ASSIGN_TO_NURSERY_SUCCESS";
export const ASSIGN_TO_NURSERY_RESET = "ASSIGN_TO_NURSERY_RESET";
export const ASSIGN_TO_NURSERY_FAIL = "ASSIGN_TO_NURSERY_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";