
export const ADD_TICKET_REQUEST = "ADD_TICKET_REQUEST";
export const ADD_TICKET_SUCCESS = "ADD_TICKET_SUCCESS";
export const ADD_TICKET_RESET = "ADD_TICKET_RESET";
export const ADD_TICKET_FAIL = "ADD_TICKET_FAIL";

export const DELETE_TICKET_REQUEST = "DELETE_TICKET_REQUEST";
export const DELETE_TICKET_SUCCESS = "DELETE_TICKET_SUCCESS";
export const DELETE_TICKET_RESET = "DELETE_TICKET_RESET";
export const DELETE_TICKET_FAIL = "DELETE_TICKET_FAIL";

export const ALL_TICKETS_REQUEST = "ALL_TICKETS_REQUEST";
export const ALL_TICKETS_SUCCESS = "ALL_TICKETS_SUCCESS";
export const ALL_TICKETS_FAIL = "ALL_TICKETS_FAIL";

export const ORDER_TICKETS_REQUEST = "ORDER_TICKETS_REQUEST";
export const ORDER_TICKETS_SUCCESS = "ORDER_TICKETS_SUCCESS";
export const ORDER_TICKETS_FAIL = "ORDER_TICKETS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";